CREATE TABLE USERS (

    ID              NUMBER GENERATED ALWAYS AS IDENTITY,

    USERNAME        VARCHAR2(30)  NOT NULL,

    EMAIL           VARCHAR2(255) NOT NULL,

    PASSWORD_HASH   VARCHAR2(255) NOT NULL,

    FAILED_ATTEMPTS NUMBER DEFAULT 0 NOT NULL,

    LOCKED_UNTIL    TIMESTAMP,

    LAST_LOGIN      TIMESTAMP,

    CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    PRIMARY KEY (ID),

    CONSTRAINT UQ_USERS_USERNAME UNIQUE (USERNAME),

    CONSTRAINT UQ_USERS_EMAIL UNIQUE (EMAIL)

);

CREATE TABLE PASSWORD_RESET_TOKENS (

    ID          NUMBER GENERATED ALWAYS AS IDENTITY,

    USER_ID     NUMBER NOT NULL,

    TOKEN_HASH  VARCHAR2(255) NOT NULL,

    EXPIRES_AT  TIMESTAMP NOT NULL,

    USED_AT     TIMESTAMP,

    CREATED_AT  TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    PRIMARY KEY (ID),

    CONSTRAINT FK_RESET_TOKENS_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID),

    CONSTRAINT UQ_RESET_TOKENS_HASH UNIQUE (TOKEN_HASH)

);

CREATE INDEX IDX_RESET_TOKENS_USER ON PASSWORD_RESET_TOKENS (USER_ID);

CREATE TABLE PASSWORD_HISTORY (

    ID              NUMBER GENERATED ALWAYS AS IDENTITY,

    USER_ID         NUMBER NOT NULL,

    PASSWORD_HASH   VARCHAR2(255) NOT NULL,

    CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    PRIMARY KEY (ID),

    CONSTRAINT FK_PASSWORD_HISTORY_USER FOREIGN KEY (USER_ID) REFERENCES USERS (ID)

);

CREATE INDEX IDX_PASSWORD_HISTORY_USER ON PASSWORD_HISTORY (USER_ID);
