CREATE TABLE USERS (

    ID              NUMBER GENERATED ALWAYS AS IDENTITY,

    USERNAME        VARCHAR2(30)  NOT NULL,

    EMAIL           VARCHAR2(255) NOT NULL,

    PASSWORD_HASH   VARCHAR2(255) NOT NULL,

    FAILED_ATTEMPTS NUMBER DEFAULT 0 NOT NULL,

    LOCKED_UNTIL    TIMESTAMP,

    LAST_LOGIN      TIMESTAMP,

    CREATED_AT      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,

    PRIMARY KEY (ID),

    CONSTRAINT UQ_USERS_USERNAME UNIQUE (USERNAME),

    CONSTRAINT UQ_USERS_EMAIL UNIQUE (EMAIL)

);
